// Code generated by "stringer -type NetworkDomain"; DO NOT EDIT.

package networkdomain

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnspecifiedDomain-0]
	_ = x[BinaryDomain-1]
	_ = x[BipolarDomain-2]
	_ = x[ContinuousDomain-3]
}

const _NetworkDomain_name = "UnspecifiedDomainBinaryDomainBipolarDomainContinuousDomain"

var _NetworkDomain_index = [...]uint8{0, 17, 29, 42, 58}

func (i NetworkDomain) String() string {
	if i < 0 || i >= NetworkDomain(len(_NetworkDomain_index)-1) {
		return "NetworkDomain(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NetworkDomain_name[_NetworkDomain_index[i]:_NetworkDomain_index[i+1]]
}
